name: Environment Variables

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Enter Eniveronment Variable'
        required: true

jobs:
  environments:
    runs-on: ubuntu-latest
    environment: 
      name: ${{ github.event.inputs.message }}
    steps:
    - name: Echo Environment URL
      run: echo "The URL for the environment is $URL"
      env:
        URL: ${{ variables.URL }}
    