name: Environment Variables Example

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Input your environment name'
        required: true
        default: 'DEV'

jobs:
  environments:
    runs-on: ubuntu-latest
    environment: 
      name: ${{ github.event.inputs.message }}
    steps:
      - name: Echo Environment Variable
        run: echo "The Value is $URL"
        env:
          URL: ${{ env.URL }}
