name: ENV URLS

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Input your environment name'
        required: true
        default: 'DEV'

jobs:
  environments:
    runs-on: ubuntu-latest
    environment: 
      name: ${{ github.event.inputs.message }}
    steps:
      - name: Echo ${{ github.event.inputs.message }} URL
        run: echo "The URL is $URL"
        env:
          URL: ${{ vars.URL }}
