name: InputPipeline

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Message to display'
        required: true
        default: "Hellow World"

jobs:
    test:
        runs-on: ubuntu-latest
    
        steps:
        - name: Input Data
          run: echo "${{ github.event.inputs.message }}"