name: Input Message

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Message to display'
        required: true

jobs:
  display:
    runs-on: ubuntu-latest
    steps:
    - name: Display Message
      run: echo "${{ github.event.inputs.message }}"